#!/bin/sh

rm -fr src/*.o src/*.so src/symbols.rds RcppSpdlog.Rcheck/ src/Makevars

#rm -rf vignettes/auto/ vignettes/*.log vignettes/*.aux vignettes/*.out vignettes/*.tex

find . -name \*~ -exec rm {} \;
