altdoc: 0.7.0
last_built: 2026-01-15T14:30:08+0000
urls:
  reference: https://eddelbuettel.github.io/rcppspdlog/man
  article: https://eddelbuettel.github.io/rcppspdlog/vignettes
pandoc: 3.1.3
pkgdown: 2.1.3
pkgdown_sha: ~
