# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fourth Example
#'
#' A simple example invoking a derived Rcpp logger.
#'
#' Note that this no longer triggers R warnings thanks to excellent help by
#' Gabi Melman.
#' @return None
#' @examples
#' exampleFour()
exampleFour <- function() {
    invisible(.Call(`_RcppSpdlog_exampleFour`))
}

